name: Merge Ready

on: pull_request_target

# Declare default permissions as read only.
permissions: {}

jobs:
  status:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/unified-status-check@03b8a7dffd1205e061f0bee949024ebefc2a6592
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
